# Manifold -- generated type stubs. Do not edit.
#
# Written from the engine's own class registry by `manifold --stubs`,
# so this file describes exactly the classes, methods and properties
# the running engine exposes -- plugins included, if they were loaded
# when it was generated. Regenerate it when the engine changes.
#
# Put it next to your scripts, or anywhere on the type checker's path,
# and an editor will complete `mf.` correctly.

from types import SimpleNamespace
from typing import Any

version: str
Key: SimpleNamespace

# ------------------------------------------------------------ values
#
# Small value types. They are copied, not referenced: reading
# `node.position` gives a Vec3 that is not the node's, so mutating it
# changes nothing -- assign the whole property back.

class _Value:
    def __init__(self, *args: Any) -> None: ...
    def as_tuple(self) -> tuple[float, ...]: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

class _Vector(_Value):
    def length(self) -> float: ...
    def normalized(self) -> Any: ...
    def dot(self, other: Any) -> float: ...
    def cross(self, other: Any) -> Any: ...
    def __add__(self, other: Any) -> Any: ...
    def __sub__(self, other: Any) -> Any: ...
    def __mul__(self, other: Any) -> Any: ...
    def __rmul__(self, other: Any) -> Any: ...
    def __truediv__(self, other: Any) -> Any: ...
    def __neg__(self) -> Any: ...

class Vec2(_Vector):
    x: float
    y: float
    def __init__(self, x: float = 0, y: float = 0) -> None: ...

class Vec3(_Vector):
    x: float
    y: float
    z: float
    def __init__(self, x: float = 0, y: float = 0, z: float = 0) -> None: ...

class Vec4(_Vector):
    x: float
    y: float
    z: float
    w: float
    def __init__(self, x: float = 0, y: float = 0, z: float = 0,
                 w: float = 0) -> None: ...

class Color(_Vector):
    r: float
    g: float
    b: float
    a: float
    def __init__(self, r: float = 0, g: float = 0, b: float = 0,
                 a: float = 1) -> None: ...

class Quat(_Value):
    x: float
    y: float
    z: float
    w: float
    def __init__(self, x: float = 0, y: float = 0, z: float = 0,
                 w: float = 1) -> None: ...

class Basis(_Value):
    def __init__(self) -> None: ...

class Transform3D(_Value):
    origin: Vec3
    basis: Basis
    def __init__(self, origin_or_basis: Any = ..., origin: Vec3 = ...) -> None: ...

class Plane(_Value):
    normal: Vec3
    d: float
    def __init__(self, normal: Vec3 = ..., d: float = 0) -> None: ...

class AABB(_Value):
    min: Vec3
    max: Vec3
    def __init__(self, lo: Vec3 = ..., hi: Vec3 = ...) -> None: ...

class Rect2(_Value):
    x: float
    y: float
    width: float
    height: float
    def __init__(self, x: float = 0, y: float = 0, w: float = 0,
                 h: float = 0) -> None: ...

class Projection(_Value):
    def __init__(self) -> None: ...

# ----------------------------------------------------------- classes

class Object:
    pass

class Material(Object):
    albedo: Color
    metallic: float  # range:0,1
    roughness: float  # range:0,1
    emissive: Color
    emissive_strength: float  # range:0,32
    normal_scale: float  # range:0,4
    occlusion_strength: float  # range:0,1
    uv_scale: Vec2
    uv_offset: Vec2
    alpha_cutoff: float  # range:0,1
    unlit: bool
    double_sided: bool
    cast_shadows: bool
    shader: str

    def __init__(self) -> None: ...
    def touch(self) -> None: ...

class Mesh(Object):
    bounds: AABB
    vertex_count: int
    triangle_count: int
    uploaded: bool

    def __init__(self) -> None: ...
    def clear(self) -> None: ...
    def compute_normals(self, smooth_angle: float = 1.0472) -> None: ...
    def compute_tangents(self) -> None: ...
    def compute_bounds(self) -> None: ...
    def weld(self, epsilon: float = 1e-05) -> int: ...
    def flip_winding(self) -> None: ...
    def transform(self, transform: Transform3D) -> None: ...

class Node(Object):
    process: bool
    physics_process: bool

    def __init__(self) -> None: ...
    def set_name(self, name: str) -> None: ...
    def get_name(self) -> str: ...
    def get_path(self) -> str: ...
    def add_child(self, child: Node | None) -> None: ...
    def remove_child(self, child: Node | None) -> None: ...
    def queue_free(self) -> None: ...
    def get_parent(self) -> Node | None: ...
    def get_child_count(self) -> int: ...
    def get_child(self, index: int) -> Node | None: ...
    def find_child(self, name: str) -> Node | None: ...
    def get_node(self, path: str) -> Node | None: ...
    def find_by_class(self, class_name: str) -> Node | None: ...
    def add_to_group(self, group: str) -> None: ...
    def remove_from_group(self, group: str) -> None: ...
    def is_in_group(self, group: str) -> bool: ...
    def is_inside_tree(self) -> bool: ...
    def print_tree(self, indent: int = 0) -> str: ...
    # signals: tree_entered, tree_exiting

class PhysicsWorld(Object):
    max_portal_hops: int

    def __init__(self) -> None: ...
    def trace(self, from_point: Vec3, to_point: Vec3, mask: int = 4294967295) -> dict: ...
    def raycast(self, from_point: Vec3, to_point: Vec3, mask: int = 4294967295) -> dict: ...
    def add_sphere(self, at: Vec3, radius: float, layer: int = 1) -> int: ...
    def add_box(self, at: Transform3D, half_extents: Vec3, layer: int = 1) -> int: ...
    def add_capsule(self, at: Transform3D, radius: float, height: float, layer: int = 1) -> int: ...
    def add_portal(self, portal: Portal3D | None) -> None: ...
    def remove_portal(self, portal: Portal3D | None) -> None: ...
    def remove_collider(self, collider: int) -> None: ...
    def set_collider_transform(self, collider: int, transform: Transform3D) -> None: ...
    def collider_count(self) -> int: ...
    def report(self) -> str: ...

class Texture(Object):
    width: int
    height: int
    path: str
    valid: bool

class Node3D(Node):
    transform: Transform3D
    global_transform: Transform3D
    position: Vec3
    global_position: Vec3
    basis: Basis
    rotation: Quat
    euler: Vec3
    scale: float
    visible: bool
    layers: int

    def __init__(self) -> None: ...
    def translate(self, delta: Vec3) -> None: ...
    def rotate(self, axis: Vec3, angle: float) -> None: ...
    def look_at(self, target: Vec3, up: Vec3 = ...) -> None: ...
    def forward(self) -> Vec3: ...
    def up(self) -> Vec3: ...
    def right(self) -> Vec3: ...
    def is_visible_in_tree(self) -> bool: ...

class Camera3D(Node3D):
    fov: float  # range:1,179
    near: float
    far: float
    ortho_height: float
    frustum_offset: Vec2
    cull_mask: int
    scale_clip_planes: bool
    mode: int
    current: bool

    def __init__(self) -> None: ...
    def make_current(self) -> None: ...
    def get_projection(self, a0: float) -> Projection: ...
    def set_custom_projection(self, projection: Projection) -> None: ...
    def get_view_matrix(self) -> Transform3D: ...
    def project_point(self, world: Vec3, aspect: float) -> Vec3: ...

class CharacterBody3D(Node3D):
    radius: float
    height: float
    velocity: Vec3
    gravity: float
    step_height: float
    max_slope: float
    collision_mask: int
    min_size: float
    max_size: float
    size: float

    def __init__(self) -> None: ...
    def move_and_slide(self, world: PhysicsWorld | None, dt: float) -> bool: ...
    def is_on_floor(self) -> bool: ...
    def is_on_wall(self) -> bool: ...
    def is_on_ceiling(self) -> bool: ...
    def get_floor_normal(self) -> Vec3: ...
    def world_radius(self) -> float: ...
    def world_height(self) -> float: ...
    def eye_height(self) -> float: ...
    def scaled(self, value: float) -> float: ...
    def portals_traversed(self) -> int: ...
    # signals: portal_traversed

class Light3D(Node3D):
    colour: Color
    energy: float  # range:0,64
    shadows: bool
    shadow_bias: float
    shadow_normal_bias: float

class MeshInstance3D(Node3D):
    mesh: Mesh | None
    cast_shadows: bool
    receive_shadows: bool
    tint: Color

    def __init__(self) -> None: ...
    def set_material(self, slot: int, material: Material | None) -> None: ...
    def get_material(self, slot: int) -> Material | None: ...
    def get_material_count(self) -> int: ...
    def get_world_bounds(self) -> AABB: ...

class Portal3D(Node3D):
    width: float  # range:0.05,64
    height: float  # range:0.05,64
    active: bool
    max_recursion: int  # range:0,8
    edge_colour: Color
    edge_width: float  # range:0,0.5
    open: float  # range:0,1

    def __init__(self) -> None: ...
    def link_to(self, other: Portal3D | None) -> None: ...
    def unlink(self) -> None: ...
    def get_link(self) -> Portal3D | None: ...
    def is_linked(self) -> bool: ...
    def get_normal(self) -> Vec3: ...
    def get_plane(self) -> Plane: ...
    def get_bounds(self) -> AABB: ...
    def world_width(self) -> float: ...
    def world_height(self) -> float: ...
    def warp_out(self) -> Transform3D: ...
    def scale_out(self) -> float: ...
    def within_aperture(self, world_point: Vec3, margin: float = 0) -> bool: ...
    def closest_point(self, world_point: Vec3) -> Vec3: ...
    def faces(self, point: Vec3) -> bool: ...
    # signals: traversed

class StaticBody3D(Node3D):
    def __init__(self) -> None: ...
    def build_from_mesh(self, world: PhysicsWorld | None, mesh: Mesh | None, layer: int = 1) -> None: ...
    def release(self) -> None: ...

class VoxelTerrain3D(Node3D):
    chunk_resolution: int  # range:8,64
    cell_size: float  # range:0.1,8
    view_distance: float  # range:32,2048
    queue_per_frame: int  # range:1,64
    max_in_flight: int  # range:0,256
    upload_per_frame: int  # range:1,32
    generate_collision: bool
    collision_distance: float

    def __init__(self) -> None: ...
    def set_viewer(self, node: Node3D | None) -> None: ...
    def set_seed(self, seed: int) -> None: ...
    def dig(self, centre: Vec3, radius: float) -> None: ...
    def build(self, centre: Vec3, radius: float, material: int = 3) -> None: ...
    def paint(self, centre: Vec3, radius: float, material: int = 3) -> None: ...
    def clear_edits(self) -> None: ...
    def rebuild(self) -> None: ...
    def wait_for_chunks(self) -> None: ...
    def height_at(self, x: float, z: float) -> float: ...
    def distance_at(self, point: Vec3) -> float: ...
    def material_at(self, point: Vec3) -> int: ...
    def set_material(self, material: Material | None) -> None: ...
    def report(self) -> str: ...

class DirectionalLight3D(Light3D):
    shadow_distance: float
    cascade_splits: Vec4
    cascade_count: int  # range:1,4

    def __init__(self) -> None: ...
    def direction(self) -> Vec3: ...

class OmniLight3D(Light3D):
    range: float
    attenuation: float
    radius: float
    def __init__(self) -> None: ...

class SpotLight3D(OmniLight3D):
    angle: float
    angle_softness: float
    def __init__(self) -> None: ...

# --------------------------------------------------------- the module

def log(message: str) -> None:
    """Write a line to the engine log."""

def warn(message: str) -> None:
    """Write a warning."""

def error(message: str) -> None:
    """Write an error."""

def root() -> Node | None:
    """The scene tree's root node."""

def scene() -> Node | None:
    """The current scene's root node."""

def physics() -> Object | None:
    """The physics world."""

def camera() -> Camera3D | None:
    """The active camera."""

def instantiate(class_name: str) -> Object | None:
    """Make an instance of an engine class by name."""

def classes() -> list[str]:
    """Every registered class name."""

def group(name: str) -> list[Node]:
    """Every node in a group."""

def key_down(key: int) -> bool:
    """Is a key held?"""

def action_down(action: str) -> bool:
    """Is an action held?"""

def action_pressed(action: str) -> bool:
    """Was an action pressed this frame?"""

def action_vector(neg_x: str, pos_x: str, neg_y: str, pos_y: str) -> Vec2:
    """A movement vector from four actions."""

def bind_action(action: str, key: int) -> None:
    """Bind a key to an action."""

def mouse_motion() -> Vec2:
    """Mouse movement since the last frame."""

def time() -> float:
    """Seconds since the scene started."""

def fps() -> float:
    """Smoothed frames per second."""

def frame() -> int:
    """The frame number."""
