#!/usr/bin/env python3
"""Generate Manifold's OpenGL loader.

Reads tools/glfns.txt -- the list of entry points the engine is allowed
to call -- and the vendored Khronos header, and writes a header of
function pointers and a loader that fills them in.

Why generate rather than vendor a loader: the generated file is exactly
as large as the engine's actual dependency on OpenGL, a name that does
not exist in the header is a build failure here rather than a null call
at run time, and there is no third-party loader to keep in step with the
header.
"""
import re
import sys
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
HEADER = os.path.join(ROOT, "third_party", "GL", "glcorearb.h")
MANIFEST = os.path.join(HERE, "glfns.txt")
OUT_H = os.path.join(ROOT, "src", "rhi", "gl", "glfn.h")
OUT_C = os.path.join(ROOT, "src", "rhi", "gl", "glfn.cpp")

# typedef void (APIENTRYP PFNGLCREATEBUFFERSPROC) (GLsizei n, GLuint *buffers);
TYPEDEF = re.compile(
    r"typedef\s+(?P<ret>[\w\s\*]+?)\s*\(\s*APIENTRYP\s+(?P<pfn>PFNGL\w+PROC)\s*\)"
)


def main() -> int:
    src = open(HEADER).read()
    # PFN name -> present in header
    known = set(m.group("pfn") for m in TYPEDEF.finditer(src))

    names = []
    for line in open(MANIFEST):
        line = line.split("#")[0].strip()
        if line:
            names.append(line)

    missing = []
    entries = []
    for n in names:
        pfn = "PFN" + n.upper() + "PROC"
        if pfn not in known:
            missing.append(n)
            continue
        entries.append((n, pfn))

    if missing:
        sys.stderr.write(
            "gen_gl: not in %s:\n  %s\n" % (HEADER, "\n  ".join(missing))
        )
        return 1

    guard = "MANIFOLD_GLFN_H"
    h = [
        "/* GENERATED by tools/gen_gl.py from tools/glfns.txt. Do not edit. */",
        "#ifndef %s" % guard,
        "#define %s" % guard,
        "",
        "/* The Khronos header gives the types and the enums; it declares no",
        " * prototypes unless asked, so the pointers below own these names. */",
        "#include <GL/glcorearb.h>",
        "",
        "namespace mf::gl {",
        "",
        "/* Fill every pointer below. `getproc` is the platform's resolver",
        " * (SDL_GL_GetProcAddress). Returns the number that came back null,",
        " * which on a conforming 4.5 context is zero. */",
        "int load(void *(*getproc)(const char *));",
        "",
        "/* Names that failed to resolve, for the error message. */",
        "const char *const *missing(int *count);",
        "",
        "}  // namespace mf::gl",
        "",
        "extern \"C\" {",
        "",
    ]
    for n, pfn in entries:
        h.append("extern %s mf_%s;" % (pfn, n))
    h += ["", "}  // extern \"C\"", ""]
    h.append("/* Call them by their real names. The indirection is invisible to")
    h.append(" * the renderer, which reads as ordinary OpenGL. */")
    for n, _ in entries:
        h.append("#define %s mf_%s" % (n, n))
    h += ["", "#endif  /* %s */" % guard, ""]

    c = [
        "/* GENERATED by tools/gen_gl.py from tools/glfns.txt. Do not edit. */",
        "#include \"glfn.h\"",
        "",
    ]
    # The macros would rewrite the definitions too.
    for n, _ in entries:
        c.append("#undef %s" % n)
    c += ["", "extern \"C\" {", ""]
    for n, pfn in entries:
        c.append("%s mf_%s = nullptr;" % (pfn, n))
    c += ["", "}  // extern \"C\"", "", "namespace mf::gl {", ""]
    c.append("static const char *s_missing[%d];" % (len(entries) + 1))
    c.append("static int s_missing_n = 0;")
    c.append("")
    c.append("int load(void *(*getproc)(const char *)) {")
    c.append("    s_missing_n = 0;")
    for n, pfn in entries:
        c.append("    mf_%s = (%s)getproc(\"%s\");" % (n, pfn, n))
        c.append("    if (!mf_%s) s_missing[s_missing_n++] = \"%s\";" % (n, n))
    c.append("    return s_missing_n;")
    c.append("}")
    c.append("")
    c.append("const char *const *missing(int *count) {")
    c.append("    if (count) *count = s_missing_n;")
    c.append("    return s_missing;")
    c.append("}")
    c.append("")
    c.append("}  // namespace mf::gl")
    c.append("")

    os.makedirs(os.path.dirname(OUT_H), exist_ok=True)
    open(OUT_H, "w").write("\n".join(h))
    open(OUT_C, "w").write("\n".join(c))
    print("gen_gl: %d entry points -> %s, %s" % (len(entries), OUT_H, OUT_C))
    return 0


if __name__ == "__main__":
    sys.exit(main())
