#!/usr/bin/env python3
"""Generate Manifold's Vulkan loader.

Same idea as tools/gen_gl.py: the manifest is the engine's entire
dependency on Vulkan, a name that is not in the header is a build
error, and nothing is linked at load time -- vkGetInstanceProcAddr is
fetched from the shared library by hand, so a machine with no Vulkan
driver starts and uses OpenGL instead of failing to launch.

The three scopes matter. A device-level function resolved through
vkGetInstanceProcAddr goes through the loader's dispatch trampoline on
every call; resolved through vkGetDeviceProcAddr it is the driver's own
function pointer. In a frame with thousands of vkCmd* calls that is a
real difference, and it costs nothing to get right.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
MANIFEST = os.path.join(HERE, "vkfns.txt")
OUT_H = os.path.join(ROOT, "src", "rhi", "vk", "vkfn.h")
OUT_C = os.path.join(ROOT, "src", "rhi", "vk", "vkfn.cpp")

HEADER_CANDIDATES = [
    "/usr/include/vulkan/vulkan_core.h",
    "/usr/local/include/vulkan/vulkan_core.h",
]

TYPEDEF = re.compile(r"typedef\s+[\w\s\*]+?\s*\(VKAPI_PTR\s*\*\s*(PFN_vk\w+)\)")


def main():
    header = next((h for h in HEADER_CANDIDATES if os.path.exists(h)), None)
    if not header:
        env = os.environ.get("VULKAN_SDK")
        if env:
            cand = os.path.join(env, "include", "vulkan", "vulkan_core.h")
            if os.path.exists(cand):
                header = cand
    if not header:
        sys.stderr.write("gen_vk: no vulkan_core.h found\n")
        return 1
    known = set(m.group(1) for m in TYPEDEF.finditer(open(header).read()))

    scopes = {"global": [], "instance": [], "device": []}
    scope = None
    missing = []
    for raw in open(MANIFEST):
        line = raw.split("#")[0].strip()
        if not line:
            continue
        if line.startswith("[") and line.endswith("]"):
            scope = line[1:-1]
            if scope not in scopes:
                sys.stderr.write("gen_vk: unknown scope %s\n" % scope)
                return 1
            continue
        if scope is None:
            sys.stderr.write("gen_vk: '%s' before any scope\n" % line)
            return 1
        pfn = "PFN_" + line
        if pfn not in known:
            missing.append(line)
            continue
        scopes[scope].append((line, pfn))

    if missing:
        sys.stderr.write("gen_vk: not in %s:\n  %s\n"
                         % (header, "\n  ".join(missing)))
        return 1

    total = sum(len(v) for v in scopes.values())
    h = ["/* GENERATED by tools/gen_vk.py from tools/vkfns.txt. Do not edit. */",
         "#ifndef MANIFOLD_VKFN_H", "#define MANIFOLD_VKFN_H", "",
         "#define VK_NO_PROTOTYPES 1",
         "#include <vulkan/vulkan.h>", "",
         "namespace mf::vk {", "",
         "/* Opens the platform's Vulkan library and resolves the global",
         " * functions. False means there is no usable Vulkan here, which is",
         " * a reason to use OpenGL and not a reason to stop. */",
         "bool load_global();",
         "void load_instance(VkInstance instance);",
         "void load_device(VkDevice device);",
         "void unload();",
         "/* Which of the manifest's names failed to resolve. */",
         "const char *const *missing(int *count);",
         "", "}  // namespace mf::vk", "", 'extern "C" {', ""]
    for scope in ("global", "instance", "device"):
        h.append("/* %s scope */" % scope)
        for name, pfn in scopes[scope]:
            h.append("extern %s mf_%s;" % (pfn, name))
        h.append("")
    h += ['}  // extern "C"', "",
          "/* Call them by their real names. */"]
    for scope in ("global", "instance", "device"):
        for name, _ in scopes[scope]:
            h.append("#define %s mf_%s" % (name, name))
    h += ["", "#endif  /* MANIFOLD_VKFN_H */", ""]

    c = ["/* GENERATED by tools/gen_vk.py from tools/vkfns.txt. Do not edit. */",
         '#include "vkfn.h"', "", "#include <cstring>", ""]
    for scope in ("global", "instance", "device"):
        for name, _ in scopes[scope]:
            c.append("#undef %s" % name)
    c += ["", "#if defined(_WIN32)", "#include <windows.h>",
          "#else", "#include <dlfcn.h>", "#endif", "", 'extern "C" {', ""]
    for scope in ("global", "instance", "device"):
        for name, pfn in scopes[scope]:
            c.append("%s mf_%s = nullptr;" % (pfn, name))
    c += ["", '}  // extern "C"', "", "namespace mf::vk {", "namespace {", ""]
    c += ["void *g_library = nullptr;",
          "PFN_vkGetInstanceProcAddr g_get_instance_proc = nullptr;",
          "const char *g_missing[%d];" % (total + 1),
          "int g_missing_n = 0;", "",
          "void *open_library() {",
          "#if defined(_WIN32)",
          '    return (void *)LoadLibraryA("vulkan-1.dll");',
          "#elif defined(__APPLE__)",
          '    void *h = dlopen("libvulkan.1.dylib", RTLD_NOW | RTLD_LOCAL);',
          '    if (!h) h = dlopen("libMoltenVK.dylib", RTLD_NOW | RTLD_LOCAL);',
          "    return h;",
          "#else",
          '    void *h = dlopen("libvulkan.so.1", RTLD_NOW | RTLD_LOCAL);',
          '    if (!h) h = dlopen("libvulkan.so", RTLD_NOW | RTLD_LOCAL);',
          "    return h;",
          "#endif",
          "}", "",
          "void *symbol(const char *name) {",
          "    if (!g_library) return nullptr;",
          "#if defined(_WIN32)",
          "    return (void *)GetProcAddress((HMODULE)g_library, name);",
          "#else",
          "    return dlsym(g_library, name);",
          "#endif",
          "}", "", "}  // namespace", ""]

    c += ["bool load_global() {",
          "    if (g_get_instance_proc) return true;",
          "    g_library = open_library();",
          "    if (!g_library) return false;",
          "    g_get_instance_proc =",
          '        (PFN_vkGetInstanceProcAddr)symbol("vkGetInstanceProcAddr");',
          "    if (!g_get_instance_proc) return false;",
          "    g_missing_n = 0;"]
    for name, pfn in scopes["global"]:
        c.append('    mf_%s = (%s)g_get_instance_proc(nullptr, "%s");' % (name, pfn, name))
        c.append('    if (!mf_%s) g_missing[g_missing_n++] = "%s";' % (name, name))
    c += ["    return mf_vkCreateInstance != nullptr;", "}", ""]

    c += ["void load_instance(VkInstance instance) {",
          "    if (!g_get_instance_proc) return;"]
    for name, pfn in scopes["instance"]:
        c.append('    mf_%s = (%s)g_get_instance_proc(instance, "%s");' % (name, pfn, name))
    c += ["}", ""]

    c += ["void load_device(VkDevice device) {",
          "    if (!mf_vkGetDeviceProcAddr) return;",
          "    // Device scope, resolved from the device: no trampoline.",]
    for name, pfn in scopes["device"]:
        c.append('    mf_%s = (%s)mf_vkGetDeviceProcAddr(device, "%s");' % (name, pfn, name))
    c += ["}", ""]

    c += ["void unload() {",
          "    if (!g_library) return;",
          "#if defined(_WIN32)",
          "    FreeLibrary((HMODULE)g_library);",
          "#else",
          "    dlclose(g_library);",
          "#endif",
          "    g_library = nullptr;",
          "    g_get_instance_proc = nullptr;",
          "}", "",
          "const char *const *missing(int *count) {",
          "    if (count) *count = g_missing_n;",
          "    return g_missing;",
          "}", "", "}  // namespace mf::vk", ""]

    os.makedirs(os.path.dirname(OUT_H), exist_ok=True)
    open(OUT_H, "w").write("\n".join(h))
    open(OUT_C, "w").write("\n".join(c))
    print("gen_vk: %d entry points (%d global, %d instance, %d device) -> %s"
          % (total, len(scopes["global"]), len(scopes["instance"]),
             len(scopes["device"]), OUT_H))
    return 0


if __name__ == "__main__":
    sys.exit(main())
